# Generated by Django 4.0.4 on 2022-05-26 09:07

import core.filters_models.decimal_range_field
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('balance', core.filters_models.decimal_range_field.DecimalRangeField(decimal_places=2, default=0.0, max_digits=20)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('email', models.EmailField(max_length=254)),
                ('specification', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowroomCarForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_car', models.PositiveIntegerField()),
                ('price', core.filters_models.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.car')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
        ),
        migrations.AddField(
            model_name='showroom',
            name='cars',
            field=models.ManyToManyField(through='showroom.ShowroomCarForSale', to='dealer.car'),
        ),
        migrations.CreateModel(
            name='DiscountShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('amount_of_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_showrooms_id_car', to='dealer.car')),
                ('id_showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_id_showroom', to='showroom.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
