version: '3'

services:
  database:
    image: postgres:latest
    container_name: db_car_sr
    env_file: .env.db
    volumes:
      - pg_data:/var/lib/posgresql/data
    expose:
      - 5432
    restart: unless-stopped

  django_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: "gunicorn -c gunicorn.py car_showroom_app.wsgi"
    env_file: .env.app
    tty: true
    stdin_open: true
    volumes:
      - ./:/app/
      - static_volume:/etc/staticfiles
    expose:
      - 8000

  nginx:
    build: ./nginx
    depends_on:
      - django_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/app/nginx/conf.d
      - static_volume:/etc/staticfiles


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '127.0.0.1:6379:6379'
    restart: unless-stopped

  celery:
    container_name: celery
    volumes:
      - ./:/app/
    build:
      context: .
      dockerfile: Dockerfile.tasks
    command: celery -A car_showroom_app worker -l INFO
    env_file: .env.app
    depends_on:
      - django_server
      - database
      - redis
    restart: unless-stopped

  tasks_beat:
    container_name: tasks_beat
    volumes:
      - ./:/app/
    build:
      context: .
      dockerfile: Dockerfile.tasks
    command: celery -A car_showroom_app beat -l info -s "/tmp/celerybeat-schedule"
    env_file: .env.app
    depends_on:
      - django_server
      - database
      - redis
    restart: unless-stopped

volumes:
  static_volume:
    driver: local
  pg_data:
    driver: local