# Generated by Django 4.0.4 on 2022-05-26 16:17

import core.filters_models.decimal_range_field
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('balance', core.filters_models.decimal_range_field.DecimalRangeField(decimal_places=2, default=0.0, max_digits=20)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(150)])),
                ('sex', models.CharField(max_length=6)),
                ('driver_licence', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('price', core.filters_models.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20)),
                ('id_buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_id_buyers', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
