# Generated by Django 4.0.4 on 2022-05-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='id_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_id_car', to='dealer.car'),
        ),
    ]
