# Generated by Django 4.0.4 on 2022-05-26 16:17

import core.filters_models.decimal_range_field
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('dealer', '0001_initial'),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleShowroomToBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('price', core.filters_models.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20)),
                ('amount_of_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('id_buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_id_buyers', to='customer.customer')),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_buyer_id_car', to='dealer.car')),
                ('id_showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_buyers_id_showroom', to='showroom.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesDealerToShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('price', core.filters_models.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20)),
                ('amount_of_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_showroom_id_car', to='dealer.dealer')),
                ('id_showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_id_showroom', to='showroom.showroom')),
                ('id_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_id_dealer', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
