# Generated by Django 4.0.4 on 2022-05-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom', '0001_initial'),
        ('customer', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.carmodel')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='DTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dealer.carmodel')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
        ),
    ]
