# Generated by Django 4.0.4 on 2022-05-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('dealer', '0001_initial'),
        ('showroom', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleShowroomToBuyer',
            new_name='SalesShowroomToCustomer',
        ),
    ]
