# Generated by Django 4.0.4 on 2022-05-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('dealer', '0001_initial'),
        ('showroom', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesSupplierToShowroom',
            new_name='SalesDealerToShowroom',
        ),
    ]
