# Generated by Django 4.0.4 on 2022-05-26 16:17

import core.filters_models.decimal_range_field
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(3000)])),
                ('engine', core.filters_models.decimal_range_field.DecimalRangeField(decimal_places=1, max_digits=3)),
                ('body_type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('balance', core.filters_models.decimal_range_field.DecimalRangeField(decimal_places=2, default=0.0, max_digits=20)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('email', models.EmailField(max_length=254)),
                ('found_year', models.DateField()),
                ('description', models.TextField(null=True)),
                ('number_of_buyers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('amount_of_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_dealer_id_car', to='dealer.car')),
                ('id_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_id_dealer', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealerCarForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', core.filters_models.decimal_range_field.DecimalRangeField(decimal_places=2, max_digits=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.car')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
        ),
        migrations.AddField(
            model_name='dealer',
            name='cars',
            field=models.ManyToManyField(through='dealer.DealerCarForSale', to='dealer.car'),
        ),
    ]
