# Generated by Django 4.0.4 on 2022-05-24 18:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('found_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('found_year', models.DateField()),
                ('address', django_countries.fields.CountryField(max_length=2)),
                ('count_sr', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='DPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dealer.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dealer.dprice')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='dealer.make'),
        ),
    ]
